#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

echo "== RoofLeadHQ Native Workflow Fixture Fresh Execution Pre-Run Guard Build 149 Build 146 Fresh-Chain Wiring Correction Approval Capture Dry Run =="
echo "Mode: local fresh execution pre-run guard after build 149 build 146 fresh-chain wiring correction approval capture only; review-only; not runner execution; not activation; non-executing."
echo "This wrapper validates committed fresh execution pre-run guard after Build 149 Build 146 fresh-chain wiring correction approval capture packet artifacts — it does NOT run the runner, invoke the exact approved command, or execute activation."
echo "No external calls, no credentials, no production data, no roofer/homeowner contact, no SMS/email/calls/calendar booking."
echo "source_of_truth_commit is 09bf972. Build 150 capture fresh runner-execution approval after Build 149 Build 146 fresh-chain wiring correction (09bf972, closed) is referenced and verified."
echo "Build 149 fresh runner-execution decision after Build 146 fresh-chain wiring correction (df9fee3, closed), Build 148 runner execution path after Build 146 fresh-chain wiring correction (135b26c, closed), Build 147 post-Build-146 blocked command evidence (0c6abaf, closed), Build 146 fresh execution pre-run guard after Build 144 Build 141 fresh-chain wiring correction (628436a, not reusable), and Build 103 runner scaffolding build (145bf15) are referenced."
echo "signed_approval_capture_source is chat."
echo "approval_scope is fresh_run_actual_external_sandbox_30_scenario_validation_once_only_after_build_146_fresh_chain_wiring_correction."
echo "fresh_runner_execution_signed_by is Jason Lohse. fresh_runner_execution_signed_at is 06/20/2026 8:25pm MST."
echo "exact_working_directory is /root/roofleadhq."
echo "exact_command references scripts/run-native-workflow-fixture-actual-external-sandbox-30-scenario-validation.sh (documented only; not invoked by this wrapper)."
echo "exact_runner_path is scripts/run-native-workflow-fixture-actual-external-sandbox-30-scenario-validation.sh."
echo "exact_manifest_path is backend/fixtures/native-workflow-demo-roofer/actual-external-sandbox-30-scenario-validation-manifest.json."
echo "exact_scenario_count is 30."
echo "fresh_runner_execution_approval_capture_status is captured. fresh_runner_execution_jason_signed_approval_status is signed."
echo "fresh_runner_execution_exact_values_required_count is 24. fresh_runner_execution_exact_values_accepted_count is 24. fresh_runner_execution_exact_values_approved_count is 24."
echo "fresh_runner_execution_approval_status is granted_scoped_one_time_pending_fresh_execution_pre_run_guard_after_build_149_build_146_fresh_chain_wiring_correction."
echo "external_sandbox_calls_approval_status is granted_scoped_test_mode_only_after_fresh_guard (verified for future scoped run only; not performed by this packet)."
echo "credentials_access_approval_status is granted_scoped_test_mode_only_no_secret_logging_after_fresh_guard (verified for future scoped run only; not performed by this packet)."
echo "test_account_use_approval_status is granted_scoped_test_accounts_only_after_fresh_guard (verified for future scoped run only; not performed by this packet)."
echo "production_data_access_approval_status is not_granted. production_supabase_write_approval_status is not_granted."
echo "schema_auth_rls_security_change_approval_status is not_granted. live_activation_approval_status is not_granted."
echo "real_homeowner_contact_approval_status is not_granted. real_roofer_contact_approval_status is not_granted."
echo "sms_email_calls_calendar_booking_approval_status is not_granted."
echo "billing_payment_automation_approval_status is not_granted."
echo "prior_command_attempt_consumption_status is consumed_by_blocked_fail_closed_result_after_build_146_guard."
echo "prior_build_147_consumed_attempt_status is consumed."
echo "immediate_rerun_allowed is false."
echo "fresh_runner_execution_approval_required_after_build_146_fresh_chain_wiring_correction is true. fresh_execution_pre_run_guard_required_after_build_146_fresh_chain_wiring_correction is true."
echo "prior Build 148/144/145/146 approvals/guard chain are not reusable after Build 146 fresh-chain wiring correction."
echo "runner_command_path_status is corrected_fail_closed_ready_for_exact_approved_execution_after_build_149_build_146_fresh_chain_wiring_correction_guard."
echo "runner_fail_closed_sanity_check_status is blocked_exit_code_1."
echo "runner_readiness_validation_status is passed. manifest_readiness_validation_status is passed. evidence_output_path_readiness_status is passed."
echo "no_stale_runner_state_status is passed. no_immediate_runner_invocation_by_this_packet is true."
echo "fresh_execution_pre_run_guard_status is passed. fresh_execution_pre_run_guard_checks_required_count is 30."
echo "fresh_execution_pre_run_guard_checks_passed_count is 30. fresh_execution_pre_run_guard_failed_count is 0."
echo "runner_command_invoked_by_this_packet is false."
echo "runner_execution_status is not_run_by_this_packet. command_execution_status is not_run_by_this_packet."
echo "external_calls_made_by_this_packet is false. credentials_accessed_by_this_packet is false. secret_values_logged_by_this_packet is false."
echo "production_data_accessed_by_this_packet is false. real_contact_made_by_this_packet is false."
echo "sms_email_calls_calendar_booking_performed_by_this_packet is false."
echo "actual_30_scenario_external_validation remains 0 captured / 0 passed / 30 missing / not_captured_by_this_run."
echo "Live activation, real homeowner contact, real roofer contact, production Supabase writes, schema/auth/RLS/security changes, and billing/payment automation remain not_granted."
echo "demo_ready_with_live_automation_disabled preserved."
echo "future_command_status is ready_for_exact_approved_runner_execution_command_after_build_149_build_146_fresh_chain_wiring_correction_guard_review_only."
echo "approved_for_activation_now is false. Next step can be exact approved runner execution command after build 149 build 146 fresh-chain wiring correction guard review only after this packet is committed."
echo "No source-of-truth check inside this wrapper (agent worktrees can be ahead/behind main during branch review)."
echo "Full aggregate regression remains available for milestone/high-risk review (Terminal 1)."

node --check backend/scripts/verify-native-workflow-fixture-fresh-execution-pre-run-guard-after-build-149-build-146-fresh-chain-wiring-correction-approval-capture-readonly.js
echo "PASS: fresh execution pre-run guard after Build 149 Build 146 fresh-chain wiring correction approval capture verifier syntax check (node --check) succeeded."

node backend/scripts/verify-native-workflow-fixture-fresh-execution-pre-run-guard-after-build-149-build-146-fresh-chain-wiring-correction-approval-capture-readonly.js

echo "PASS: Native Workflow Fixture Fresh Execution Pre-Run Guard Build 149 Build 146 Fresh-Chain Wiring Correction Approval Capture Dry Run wrapper passed."
echo "Note: This fresh execution pre-run guard after Build 149 Build 146 fresh-chain wiring correction approval capture does NOT run the runner or invoke the exact approved command."
echo "Note: Fresh execution pre-run guard passed for scoped one-time fresh runner execution command after Build 146 fresh-chain wiring correction guard review only."
echo "Note: actual 30-scenario external validation remains 0 captured / 0 passed / 30 missing."
echo "Note: Controlled real roofer setup and live activation remain blocked."
echo "Note: Next step can be exact approved runner execution command after Build 149 Build 146 fresh-chain wiring correction guard review only after this packet is committed."