#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

echo "== RoofLeadHQ Native Workflow Fixture Fresh Runner-Execution Decision After Path Correction Dry Run =="
echo "Mode: local fresh runner-execution decision/template after path correction only; review-only; not signed; not approved; not runner execution; not activation; non-executing."
echo "This wrapper validates committed fresh runner-execution decision after path correction packet artifacts — it does NOT run the runner, capture approval, pass fresh pre-run guard, or execute activation."
echo "No external calls, no credentials, no production data, no roofer/homeowner contact, no SMS/email/calls/calendar booking."
echo "source_of_truth_commit is 750d5a5. Build 113 runner execution path correction (750d5a5, closed) is referenced and verified."
echo "Build 112 capture fresh runner command blocked evidence (847592a), Build 111 fresh execution pre-run guard (135b367), Build 110 fresh signed approval capture (a1f4dd7), and Build 103 runner scaffolding build (145bf15) are referenced."
echo "prior_runner_execution_path_correction_status is closed."
echo "prior_fresh_command_attempt_consumption_status is consumed_by_blocked_fail_closed_result."
echo "immediate_rerun_allowed is false."
echo "fresh_runner_execution_approval_required_after_path_correction is true. fresh_execution_pre_run_guard_required_after_path_correction is true."
echo "prior Build 110/111 approvals are not reusable after path correction."
echo "runner_command_path_status is corrected_fail_closed_direct_invocation_always_blocked_pending_fresh_decision_after_execution_path_correction."
echo "total_manifest_scenarios_count is 30. all_manifest_scenarios_execution_status is not_run. all_manifest_scenarios_pass_fail_status is not_captured."
echo "fresh_runner_execution_decision_template_status is created_review_only."
echo "fresh_runner_execution_approval_capture_status is not_captured. fresh_runner_execution_jason_signed_approval_status is not_signed."
echo "fresh_runner_execution_exact_values_required_count is 24. fresh_runner_execution_exact_values_accepted_count is 0. fresh_runner_execution_exact_values_approved_count is 0."
echo "fresh_runner_execution_approval_status is not_granted. fresh_execution_pre_run_guard_status is not_passed."
echo "external_sandbox_calls_approval_status is not_granted_by_this_packet. credentials_access_approval_status is not_granted_by_this_packet."
echo "test_account_use_approval_status is not_granted_by_this_packet. production_data_access_approval_status is not_granted."
echo "exact_working_directory: /root/roofleadhq"
echo "exact_runner_path: scripts/run-native-workflow-fixture-actual-external-sandbox-30-scenario-validation.sh"
echo "exact_manifest_path: backend/fixtures/native-workflow-demo-roofer/actual-external-sandbox-30-scenario-validation-manifest.json"
echo "exact_scenario_count: 30"
echo "exact_command documented (not executed from this wrapper)."
echo "Live activation, real homeowner contact, real roofer contact, production Supabase writes, schema/auth/RLS/security changes, SMS/email/calls/calendar booking, and billing/payment automation remain not_granted."
echo "demo_ready_with_live_automation_disabled preserved."
echo "actual_30_scenario_external_validation remains 0 captured / 0 passed / 30 missing / not_captured_by_this_run."
echo "future_command_status is blocked_until_fresh_runner_execution_approval_captured_after_path_correction."
echo "command_execution_status is not_run_by_this_packet. runner_execution_status is not_run_by_this_packet."
echo "runner_command_invoked_by_this_packet is false."
echo "approved_for_activation_now is false."
echo "Next step is Jason review/sign fresh runner-execution approval template after path correction, or stop/review — NOT execution."
echo "After approval capture, fresh execution pre-run guard pass is required — NOT passed by this packet."
echo "This wrapper does NOT invoke scripts/run-native-workflow-fixture-actual-external-sandbox-30-scenario-validation.sh."
echo "No source-of-truth check inside this wrapper (agent worktrees can be ahead/behind main during branch review)."
echo "Full aggregate regression remains available for milestone/high-risk review (Terminal 1)."

node --check backend/scripts/verify-native-workflow-fixture-fresh-runner-execution-decision-after-path-correction-readonly.js
echo "PASS: fresh runner-execution decision after path correction verifier syntax check (node --check) succeeded."

node backend/scripts/verify-native-workflow-fixture-fresh-runner-execution-decision-after-path-correction-readonly.js

echo "PASS: Native Workflow Fixture Fresh Runner-Execution Decision After Path Correction Dry Run wrapper passed."
echo "Note: This local fresh runner-execution decision after path correction does NOT run the runner, capture approval, or execute anything."
echo "Note: Fresh runner-execution approval is not captured and not signed."
echo "Note: Fresh execution pre-run guard is not passed by this packet."
echo "Note: Build 112 consumed the fresh attempt. Immediate rerun is not allowed."
echo "Note: actual 30-scenario external validation remains 0 captured / 0 passed / 30 missing."
echo "Note: Next step is Jason review/sign fresh runner-execution approval template after path correction, or stop/review — NOT execution."