#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

echo "== RoofLeadHQ Native Workflow Fixture Capture Fresh Runner Command Blocked Evidence Dry Run =="
echo "Mode: local blocked command evidence capture only; review-only; not rerun; not execution; not activation; non-executing."
echo "This wrapper validates committed fresh blocked command evidence packet artifacts — it does NOT run the runner, rerun the runner, or execute activation."
echo "No external calls, no credentials, no production data, no roofer/homeowner contact, no SMS/email/calls/calendar booking."
echo "No credentials or secret values are accessed by this packet."
echo "source_of_truth_commit is 135b367. Build 111 fresh execution pre-run guard packet (135b367) is referenced and verified."
echo "Build 110 fresh signed runner-execution approval capture packet (a1f4dd7) is referenced and verified."
echo "Build 108 runner state wiring correction (77f2a00) and Build 107 blocked command evidence (4a618fa) are referenced."
echo "approval_scope is fresh_run_actual_external_sandbox_30_scenario_validation_once_only."
echo "signed_approval_timestamp is 06/20/2026 9:54am MST."
echo "exact_working_directory is /root/roofleadhq."
echo "exact_command_attempted references scripts/run-native-workflow-fixture-actual-external-sandbox-30-scenario-validation.sh (documented only; not invoked or rerun by this wrapper)."
echo "fresh_runner_command_attempt_status is attempted_blocked_nonzero. fresh_runner_command_exit_status is nonzero_blocked."
echo "fresh_runner_command_attempt_consumption_status is consumed_by_blocked_fail_closed_result."
echo "runner_direct_invocation_status_after_fresh_guard is blocked_nonzero_expected."
echo "expected_repo_future_command_status_before_attempt was ready_for_exact_approved_runner_execution_command_review_only."
echo "runner_command_path_status is corrected_fail_closed_ready_for_exact_approved_execution_after_guard."
echo "fresh_runner_execution_approval_capture_status is captured. fresh_runner_execution_jason_signed_approval_status is signed."
echo "fresh_runner_execution_exact_values_required_count is 24. fresh_runner_execution_exact_values_accepted_count is 24. fresh_runner_execution_exact_values_approved_count is 24."
echo "fresh_execution_pre_run_guard_status is passed. fresh_execution_pre_run_guard_checks_required_count is 30."
echo "fresh_execution_pre_run_guard_checks_passed_count is 30. fresh_execution_pre_run_guard_failed_count is 0."
echo "no_immediate_rerun_allowed is true. no_immediate_runner_invocation_by_blocked_path is true."
echo "runner_command_invoked_by_this_packet is false. runner_command_rerun_by_this_packet is false."
echo "runner_execution_status is not_run. command_execution_status is not_run."
echo "external_calls_made_by_runner_attempt is false. credentials_accessed_by_runner_attempt is false."
echo "secret_values_logged_by_runner_attempt is false. production_data_accessed_by_runner_attempt is false."
echo "real_contact_made_by_runner_attempt is false. sms_email_calls_calendar_booking_performed_by_runner_attempt is false."
echo "validation_log_written_by_runner_attempt is false. structured_evidence_written_by_runner_attempt is false."
echo "actual_30_scenario_external_validation remains 0 captured / 0 passed / 30 missing / not_captured_by_this_run."
echo "Live activation, real homeowner contact, real roofer contact, production Supabase writes, schema/auth/RLS/security changes, and billing/payment automation remain not_granted."
echo "demo_ready_with_live_automation_disabled preserved."
echo "future_command_status is blocked_until_runner_execution_path_correction_and_fresh_decision."
echo "approved_for_activation_now is false. Next step is runner execution path correction/design and fresh decision path, not immediate rerun."
echo "No source-of-truth check inside this wrapper (agent worktrees can be ahead/behind main during branch review)."
echo "Full aggregate regression remains available for milestone/high-risk review (Terminal 1)."

node --check backend/scripts/verify-native-workflow-fixture-capture-fresh-runner-command-blocked-evidence-readonly.js
echo "PASS: capture fresh runner command blocked evidence verifier syntax check (node --check) succeeded."

node backend/scripts/verify-native-workflow-fixture-capture-fresh-runner-command-blocked-evidence-readonly.js

echo "PASS: Native Workflow Fixture Capture Fresh Runner Command Blocked Evidence Dry Run wrapper passed."
echo "Note: This packet captures the blocked fresh command attempt evidence only — it does NOT rerun the runner."
echo "Note: This packet does NOT perform actual 30-scenario validation or invoke the exact approved command."
echo "Note: actual 30-scenario external validation remains 0 captured / 0 passed / 30 missing."
echo "Note: Controlled real roofer setup and live activation remain blocked."
echo "Note: Next step is runner execution path correction/design and fresh decision path, not immediate rerun."